INSERT INTO tutorials (id, title, description, category, difficulty, duration, content, tags) VALUES
('tut1', 'Identifying Deepfake Videos', 'Learn to spot the telltale signs of deepfake manipulation in videos', 'Detection', 'beginner', 15, 'This tutorial covers the basic indicators of deepfake videos including unnatural facial movements, inconsistent lighting, and edge artifacts.', '["deepfake", "video", "detection", "basics"]'),
('tut2', 'Voice Cloning Detection', 'Advanced techniques for identifying synthetic voices', 'Detection', 'intermediate', 25, 'Explore spectral analysis, prosody patterns, and other audio forensics techniques to identify cloned voices.', '["voice", "audio", "cloning", "forensics"]'),
('tut3', 'Social Engineering Awareness', 'Understanding how deepfakes are used in social engineering attacks', 'Security', 'beginner', 20, 'Learn about common social engineering tactics that use deepfake technology to manipulate victims.', '["social engineering", "security", "awareness"]'),
('tut4', 'Legal Implications of Deepfakes', 'Understanding the legal landscape around synthetic media', 'Legal', 'advanced', 35, 'Comprehensive overview of current laws, regulations, and legal precedents regarding deepfake technology.', '["legal", "regulations", "compliance"]');

INSERT INTO case_studies (id, title, description, category, severity, media_type, victim_profile, attack_method, outcome, prevention_tips, evidence_urls, tags) VALUES
('case1', 'CEO Voice Cloning Fraud', 'A major corporation lost $2.4M to voice cloning attack', 'Financial Fraud', 'critical', 'audio', 'Corporate Finance Team', 'Voice cloning of CEO requesting urgent wire transfer', 'Successful fraud, funds recovered partially through insurance', '["Implement voice verification protocols", "Multi-factor authentication for financial transactions", "Employee training on voice cloning risks"]', '["https://example.com/evidence1", "https://example.com/evidence2"]', '["voice cloning", "financial fraud", "corporate"]'),
('case2', 'Political Deepfake Scandal', 'Fake video of politician created election controversy', 'Political Manipulation', 'high', 'video', 'Political Figure', 'High-quality deepfake video showing false statements', 'Election results questioned, legal action taken', '["Media verification protocols", "Rapid response teams", "Public education campaigns"]', '["https://example.com/evidence3"]', '["deepfake", "political", "election"]'),
('case3', 'Romance Scam Using Face Swap', 'Individual defrauded through deepfake romance scam', 'Personal Fraud', 'medium', 'image', 'Single Adult (50+)', 'Face-swapped images in dating app profile', 'Victim lost $15,000, perpetrator identified', '["Reverse image searches", "Video verification calls", "Trusted friend consultation"]', '["https://example.com/evidence4"]', '["romance scam", "face swap", "dating fraud"]');
